### ISSUE TITLE
2019.04.26 회의록

### ISSUE THREAD

**Issue by LeeYoungJik** [takamok/SWpjclass#3]

**Comment by takamok** [comment]
팀장:이영직
앱 제작(명칭 가정): 100대 명산

공공데이터 포털: 산림청 

왜?: 산림청 휴양복지 정보와 { 계절에따른 (벚꽃 및) 단풍의 개화시기 }  관광명소를 알고 산의 가치와 중요성을 알려주고 데이터를 토대로 지역경재 발전과
네이버 개화시기 정보2
java 나 안드로이드 스튜디오 사용

**Comment by LeeYoungJik** [comment]
이미지 연동을 해서 gps 값을 찾아 로드맵에 위치를 확인하는 
소프트웨어를 만들기로 결정했다.

소프트웨어 연동 과정은 다음과 같다. 

0. html사이트를 하나 생성. 여기서 아이디를 만들고, 접속한다.

1. 사이트 내에서 내가 확인할 이미지를 가져다 놓는다. (URL주소로 연동.)

2. URL주소로 이미지를 구글 맵에서 확인 후 GPS를 받아온다.

3. 받아온 GPS주소를 구글 맵에서 연동을 해서 확인한다.
사진을 GPS에 연동을 해서 GPS좌표가 찍히면은 음식점 정보나, 위치를 확인해서
사용자에게 정보를 제공한다.

**Comment by Chohankyu8285** [comment]
https://github.com/googleknowledge/qlabel
사진에 있는 글자를 찾고 그 글자를 번역하는 방법을 위해 오픈소를 찾다가 q레이블을 찾음

**Comment by LeeYoungJik** [comment]
https://www.google.com/search?source=hp&ei=FwTDXJ7rJIiQr7wP-9yl-A8&q=%EC%82%AC%EC%A7%84+%EC%9C%84%EC%B9%98+%EC%A0%95%EB%B3%B4+%ED%99%95%EC%9D%B8+%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8&oq=%EC%82%AC%EC%A7%84+%EC%9C%84%EC%B9%98+&gs_l=psy-ab.1.1.0l3j0i30l3j0i5i30l4.3814.8206..9217...4.0..0.160.2365.2j18......0....1..gws-wiz.....0..0i10j0i131j0i8i30.IPto4BtfKzg

**Comment by LeeYoungJik** [comment]
4(추가). 구글맵에서 확인한 주소의 사진을 내가 원하는 언어로 번역을 해준다.

**Comment by takamok** [comment]
-팀장 정하기-
팀장 : 강창희
-주 제-
app 제작: 한국 100대 명산
상용 공공데이터 포털: 산림청 홈페이지

제작 이유: 산림청 데이터의 휴양복지 정보와 한국의 명산으로 관광지를 알고 자연의 가치와 중요성을 알려주며 산이 위치한 지역구에 경제 활성화를 바란다. 
+추가 사항+
(naver 검색) 개화시기, 명산...
-제작-
java , 안드로이드 스튜디오 사용


ex :(꿀뷰),사진 위치 정보 확인 프로그램 검색


-주제 변경-
png등 이미지 파일을 제작물과 연동을 해서 사진의 gps 값을 찾아 구글 로드맵에 위치를 확인하는 소프트웨어를 만들기로 결정.

소프트웨어 연동 과정은 다음과 같다. 

1. html사이트를 하나 생성. 여기서 아이디를 만들고, 접속한다.
2. 사이트 내에서 내가 확인할 이미지를 가져다 놓는다.   (URL주소로 연동.)
3. URL주소로 이미지를 구글 맵에서 확인 후 GPS를 받아온다.
4. 받아온 GPS주소를 구글 맵에서 확인 가능하다.
5.** 구글map에서 확인한 주소의 사진을 내가 원하는 언어로 번역을 해준다.-- 이점이 중요 다른app과 다른점.

제작이유? 어떠한 이유로?
사진데이터를 분석해 GPS에 연동을 해서 좌표가 찍히면은 음식점 정보나, 위치를 확인하여 사용자에게 정보를 제공한다.

**Comment by Chohankyu8285** [comment]
https://cpuu.postype.com/post/23100
이미지 GPS 정보 추출

**Comment by takamok** [comment]
https://github.com/search?utf8=%E2%9C%93&q=photo+gps&type=

github에서 gps데이터 확인하기

**Comment by LeeYoungJik** [comment]
이미지 캡처, 좌표 찾기 프로그램 유튜브
https://www.youtube.com/watch?v=cBU9qlXklVs

**Comment by kangchang** [comment]
1.    1. 가출 청소년 보호서를 위한 어플을 위한 제작을 구상(청소년 위탁소, 무료 급식소 제안)-> 가출 청소년 들이 어플을 쓰고 몸을 위탁하지 않을 거라고 생각해서 아이디어 기각.
2.    2. 사진을 구글 맵에 연동해서 gps얻은후, 맵에서 그 gps를 찾아 확인한다. 확인 결과 이런 소프트웨어가 여러 개가 있는 것을 확인.  새로운 기능인 이미지 속 외국어 번역 기능을 착안..
3.    3. 생각한 소스코드를 깃허브에서 확인.
4.    https://github.com/ryanseys/photogps
5.
6.    프로그램 안의 간략한 설계도 구상.
7.    1. 사이트를 생성. 사이트 내에서 아이디로 접속.
8.    2. 사이트 내에서 이미지 파일을 가져다 놓는다.
9.    3. 이미지 파일을 구글 맵에서 확인 후 GPS를 받아온다.
10.    4. 받아온 GPS를 구글 맵에서 연동해서 확인한다.
11.    5. 구글 맵에서 확인 장소의 외국어를 번역한다.
